name: Daily Torn Company Fetch

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # every day at 00:00 UTC

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TORN_API_KEY: ${{ secrets.TORN_API_KEY }}
      GH_PAT: ${{ secrets.GH_PAT }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install requests

      - name: Run Torn script
        run: python torn_daily.py

      - name: Commit and push
        env:
    GH_PAT: ${{ secrets.GH_PAT }}
   run: |
    git config --global user.name "github-actions"
    git config --global user.email "actions@github.com"
    git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}
    git add static/daily_companies.json
    git commit -m "Update company data [skip ci]" || echo "No changes"
    git push origin HEAD:main
